### ISSUE TITLE
Cross-site Scripting (XSS) via Data URIs [SEVERITY: HIGH]

### ISSUE THREAD

**Issue by pixelass** [esdoc/esdoc-plugins#50]
https://www.bithound.io/github/sinnerschrader/esdoc-custom-theme/master/dependencies/npm/esdoc-publish-html-plugin#security-advisories

Discovered in a nested `dependency:esdoc-publish-html-plugin@1.1.0marked@0.3.6`

https://snyk.io/vuln/npm:marked:20170112?utm_source=bithound

> ### Cross-site Scripting (XSS) via Data URIs
> Affecting marked package, versions <0.3.7

**Comment by andrevenancio** [comment]
any updates on this?

**Comment by pixelass** [comment]
@andrevenancio this repo is unmaintained until the owner responds.

Try working with https://github.com/esdoc2

**Comment by pixelass** [comment]
esdoc2 is a fork of esdoc. It was created due to the lack of response and amount of open issues.
